# Clock signal
set_property PACKAGE_PIN W5 [get_ports slave_clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports slave_clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports slave_clk]
	
# Switches
set_property PACKAGE_PIN V16 [get_ports {rstn}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rstn}]
#set_property PACKAGE_PIN V16 [get_ports {slave_clk}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {slave_clk}]
set_property PACKAGE_PIN W16 [get_ports {t_start}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {t_start}]
set_property PACKAGE_PIN W17 [get_ports {d_in_s[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_in_s[0]}]
set_property PACKAGE_PIN W15 [get_ports {d_in_s[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_in_s[1]}]
set_property PACKAGE_PIN V15 [get_ports {d_in_s[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_in_s[2]}]
set_property PACKAGE_PIN W14 [get_ports {d_in_s[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_in_s[3]}]
set_property PACKAGE_PIN W13 [get_ports {d_in_s[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_in_s[4]}]
set_property PACKAGE_PIN V2 [get_ports {d_in_s[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_in_s[5]}]
set_property PACKAGE_PIN T3 [get_ports {d_in_s[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_in_s[6]}]
set_property PACKAGE_PIN T2 [get_ports {d_in_s[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_in_s[7]}]
set_property PACKAGE_PIN R3 [get_ports {t_size[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {t_size[0]}]
set_property PACKAGE_PIN W2 [get_ports {t_size[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {t_size[1]}]
set_property PACKAGE_PIN U1 [get_ports {t_size[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {t_size[2]}]	
set_property PACKAGE_PIN T1 [get_ports {mosi}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {mosi}]
	
# LEDs
set_property PACKAGE_PIN U16 [get_ports {miso}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {miso}]
set_property PACKAGE_PIN E19 [get_ports {spi_clk}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {spi_clk}]
#set_property PACKAGE_PIN U19 [get_ports {cs}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {cs}]
set_property PACKAGE_PIN U19 [get_ports {d_out_s[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out_s[0]}]
set_property PACKAGE_PIN V19 [get_ports {d_out_s[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out_s[1]}]
set_property PACKAGE_PIN W18 [get_ports {d_out_s[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out_s[2]}]
set_property PACKAGE_PIN U15 [get_ports {d_out_s[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out_s[3]}]
set_property PACKAGE_PIN U14 [get_ports {d_out_s[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out_s[4]}]
set_property PACKAGE_PIN V14 [get_ports {d_out_s[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out_s[5]}]
	_s
set_property PACKAGE_PIN V13 [get_ports {d_out_s[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out_s[6]}]
set_property PACKAGE_PIN V3 [get_ports {d_out_s[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out_s[7]}]
